# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='animal_pictures/')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('edad', models.PositiveSmallIntegerField()),
                ('fechaAdopcion', models.DateField(auto_now_add=True, verbose_name='En adopción desde')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
            },
        ),
        migrations.CreateModel(
            name='TipoDeAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de animal',
                'verbose_name_plural': 'Tipos de animales',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cholito.TipoDeAnimal'),
        ),
    ]
