# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cholito', '0003_abuso_denuncia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariomunicipalidad',
            name='foto',
            field=models.ImageField(blank=True, upload_to='municipalidad_pictures/'),
        ),
        migrations.AlterField(
            model_name='usuarioong',
            name='foto',
            field=models.ImageField(blank=True, upload_to='ong_pictures/'),
        ),
    ]
