# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cholito', '0004_auto_20171023_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarionormal',
            name='foto',
            field=models.ImageField(blank=True, upload_to='usuario_pictures/'),
        ),
    ]
